{% set name = "fastapi-mvc" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-mvc-{{ version }}.tar.gz
  sha256: f01fd5bd2eff3172e101aa09f619487f21f217a8d828db32e7e764145740c1b7

build:
  number: 0
  noarch: python
  entry_points:
    - fastapi-mvc = fastapi_mvc.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - click ~=7.1.2
    - cookiecutter ~=1.7.3
    - python >=3.7

test:
  imports:
    - fastapi_mvc
    - fastapi_mvc.cli
    - fastapi_mvc.commands
    - fastapi_mvc.exceptions
    - fastapi_mvc.generators
    - fastapi_mvc.parsers
    - fastapi_mvc.template
    - fastapi_mvc.utils
  commands:
    - pip check
    - fastapi-mvc --help
  requires:
    - pip

about:
  home: https://github.com/rszamszur/fastapi-mvc
  summary: Generate and manage FastAPI projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
