{% set name = "fastapi-mvc" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-mvc-{{ version }}.tar.gz
  sha256: a9f7c3d63fddee17968cc875c36efa23d3b0f667d587b1c3fab4a0e3c6289615

build:
  number: 0
  noarch: python
  entry_points:
    - fastapi-mvc = fastapi_mvc.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - click ~=8.1.3
    - cookiecutter ~=2.1.1
    - python >=3.7

test:
  imports:
    - fastapi_mvc
    - fastapi_mvc.cli
    - fastapi_mvc.commands
    - fastapi_mvc.generators
    - fastapi_mvc.generators.controller
    - fastapi_mvc.generators.generator
    - fastapi_mvc.parsers
    - fastapi_mvc.utils
  commands:
    - pip check
    - fastapi-mvc --help
  requires:
    - pip

about:
  home: https://github.com/rszamszur/fastapi-mvc
  summary: Generate and manage FastAPI projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
