{% set name = "fastapi-mvc" %}
{% set version = "0.22.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-mvc-{{ version }}.tar.gz
  sha256: 7dc6d2b83a4c5b05e9cd4873f57a0c703f99059b759346c5828fd72dbb667d4c

build:
  number: 0
  noarch: python
  entry_points:
    - fastapi-mvc = fastapi_mvc.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - click >=8.1.3,<8.2.0
    - copier ==6.2.0
    - python >=3.8,<4.0

test:
  imports:
    - fastapi_mvc
  commands:
    - pip check
    - fastapi-mvc --help
  requires:
    - pip

about:
  home: https://github.com/rszamszur/fastapi-mvc
  doc_url: https://fastapi-mvc.netlify.app/
  summary: Generate and manage FastAPI projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
