{% set name = "fastapi-mvc" %}
{% set version = "0.28.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c6c82650ea025cf53d532a10412fd0cd851e603c08b338c91cc5fce847fc6a6e

build:
  number: 0
  noarch: python
  entry_points:
    - fastapi-mvc = fastapi_mvc.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - click >=8.1.3,<8.2.0
    - copier ==6.2.0
    - python >=3.8,<4.0

test:
  imports:
    - fastapi_mvc
  commands:
    - pip check
    - fastapi-mvc --help
  requires:
    - pip

about:
  home: https://github.com/rszamszur/fastapi-mvc
  doc_url: https://fastapi-mvc.netlify.app/
  summary: Generate and manage FastAPI projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
